version: '3'

services:

  tomcat:
    environment:
      - KM_ENVDB_PORT=5432
      - KM_ENVDB_HOST=${KM_APP_NAME}-db
      - KM_DEFAULT_ENV_ID=0010000000002
      - KM_ROOTDIR=/usr/local/tomcat/webapps/ROOT
      - KM_KOLLDIR=/usr/local/tomcat/webapps/koll
      - KM_LIB_DIR=/usr/local/tomcat/webapps/lib
      - KM_DB_PWD=${KM_DB_PWD}
      - KM_APP_NAME=${KM_APP_NAME}
    container_name: $KM_APP_NAME-tomcat
    build: ./images/tomcat
    # the image name has to contain the ghrc.io/kommetio part because it is required for it to be pushed to container registry
    image: ghcr.io/kommetio/km-tomcat:latest
    volumes:
      - ${KM_VOLUME}/bin/km-1.0.war:/usr/local/tomcat/webapps/ROOT.war
      - ${KM_VOLUME}/tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh
    ports:
      - ${KM_TOMCAT_PORT}:8080
    depends_on:
      - db

  apache:
    container_name: $KM_APP_NAME-httpd
    build: ./images/httpd
    image: ghcr.io/kommetio/km-httpd:latest
    volumes:
      - ${KM_VOLUME}/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ${KM_VOLUME}/ssl:/home/ssl
    ports:
      - ${KM_HTTPD_PORT}:80

  db:
    container_name: $KM_APP_NAME-db
    restart: always
    build: ./images/psql
    image: ghcr.io/kommetio/km-db:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ${KM_VOLUME}/db/data:/var/lib/postgresql/data
      - ${KM_VOLUME}/db/scripts:/home/db/scripts
      - ${KM_VOLUME}/db/dbtemplates:/home/db/dbtemplates
    ports:
      - ${KM_DB_PORT}:5432

volumes:
    postgres-data: {}
