name: Build collective image
on: [push]
jobs:
        build-image:
                runs-on: ubuntu-latest
                steps:
                        - name: get-repo
                          uses: actions/checkout@v2
                          with:
                                repository: kommetio/kommet
                                ref: refs/tags/latest-build
                                token: ${{ secrets.KOMMET_REPO_TOKEN }}
                                path: kommet-repo
                                #clean: false # keep it for further steps
                        - name: build-kommet-war
                          run: |
                                cd kommet-repo
                                echo "Building app from source"
                                mvn package -DskipTests=true

                        - name: checkout-docker-repo
                          uses: actions/checkout@v2
                          with:
                                path: kommet-docker-repo
                                #clean: false # keep it for further steps
                        - name: Building images
                          run: |
                                cd kommet-docker-repo
                                cp ../kommet-repo/target/km-1.0.war images/collective
                                cd images/collective
                                chmod 777 build-image.sh
                                ./build-image.sh "mockpwd" "kommet/kommet:latest"

                        - name: Log in to Docker Hub
                          uses: docker/login-action@v2
                          with:
                            username: ${{ secrets.DOCKER_USERNAME }}
                            password: ${{ secrets.DOCKER_PWD }}

                        - name: Push image
                          run: |
                                cd kommet-docker-repo/images/collective
                                docker push kommet/kommet:latest
